project:
  type: book
  pre-render: R/helper.R


book:
  title: "Notes on Bayes Rules!"
  author: "Peter Baumgartner"
  date: last-modified
  cover-image: img/cover.png
  date-format: YYYY-MM-DD HH:mm
  favicon: "include/favicon_io/apple-touch-icon.png"
  site-url: https://pbaumgartner-bayes-rules.share.connect.posit.cloud/
  repo-url: https://github.com/petzi53/bayes-rules
  repo-branch: main
  repo-actions: [edit, issue, source]
  page-navigation: true

  chapters:
    - index.qmd
    - part: "I Bayesian Foundations"
      chapters:
        - 001-big-picture.qmd
        - 002-bayes-rule.qmd
        - 003-beta-binomial.qmd
        - 004-balance-sequentiality.qmd
        - 005-conjugate-families.qmd
  appendices:
      - 900-used-packages.qmd
      - 990-webexercises.qmd


bibliography:
    - references.bib
reference-section-title: References
# citeproc: true


format:
  html:
    theme: cosmo
    highlight-style: atom-one
    css:
     - include/quarto.css
     - include/glossary.css
     - include/webex.css
    number-sections: true
    toc-depth: 5
    toc-expand: 4
    toc_float: true
    code-fold: true
    code-summary: "Show/hide the code"
    code-tools: true
    code-link: true
    code-overflow: scroll
    df-print: default
    link-external-newwindow: true
    link-external-icon: true
    include-after-body: include/webex.js

filters:
   - include-code-files
   - section-bibliographies
   - shinylive
   - base64

knitr:
  opts_chunk:
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true

editor: source

execute:
    freeze: auto
    echo: true
### for test purpose / cleaning up
#    cache: false

lightbox: true



crossref:
  appendix-title: "Appendix"
  appendix-delim: ":"
  custom:
    - kind: float
      reference-prefix: Important
      key: imp
    - kind: float
      reference-prefix: Commitment
      key: com
    - kind: float
      reference-prefix: Report
      key: rep
    - kind: float
      reference-prefix: Resource
      key: res
    - kind: float
      reference-prefix: Package Profile
      key: pak
    - kind: float
      reference-prefix: Bullet List
      key: bul
    - kind: float
      reference-prefix: Numerical List
      key: num
    - kind: float
      reference-prefix: Note
      key: not
    - kind: float
      reference-prefix: Explanation
      key: exp
    - kind: float
      reference-prefix: Tip
      key: tip
    - kind: float
      reference-prefix: Checklist
      key: tdo
    - kind: float
      reference-prefix: Collection Code
      key: col
    - kind: float
      reference-prefix: Watch-out
      key: wat
    - kind: float
      reference-prefix: Paragraph
      key: par

tip-cap-location: top
pak-cap-location: top
bul-cap-location: bottom

# https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml
language:
   crossref-cnj-title: "R Code"             # replaces "Conjecture"  num-r-code
   crossref-cor-title: "Quiz Yourself!"     # replaces "Corollary    num-assessment
   crossref-def-title: "Experiment"         # replaces "Definition"  num-experiment
   crossref-exm-title: "Code Collection"    # replaces  "Example"    num-code-collection
   crossref-exr-title: "Exercise"           # remains  "Exercise"    num-exercise
   crossref-fig-title: "Figure"             # remains  "Figure"      fig
   crossref-lem-title: "Resource"           # replaces "Lemma"       num-ressource
   crossref-lst-title: "Listing"            # remains  "Listing"     lst
   crossref-prp-title: "Procedure"          # replaces "Proposition" num-procedure
   crossref-tbl-title: "Table"              # remains  "Table"       tbl
   crossref-thm-title: "Formula"            # replaces "Theorem"     num-theorem
#   crossref-int-title: "Interpretation"

   callout-tip-title: "Tip"                 # green
   callout-note-title: "Note"               # blue
   callout-warning-title: "Warning"         # orange
   callout-important-title: "Important"     # red
   callout-caution-title: "Caution"         # yellow
